const GAME_CARD_HEIGHT_BASE = 150

export const GameConstants = {
    GAME_CARD_HEIGHT: GAME_CARD_HEIGHT_BASE,
    GAME_CARD_WIDTH: GAME_CARD_HEIGHT_BASE / 18 * 13,
    GAME_SCREEN_WIDTH: 800,
    GAME_SCREEN_HEIGHT: 800,

}